#include <stdio.h>
char a[20];
char b[20];
char c[20];
char d[20];
char e[20];
char f[20];
char g[20];
char h[20];
char i[20];
char j[20];
char k[20];
char l[20];
char m[20];
char n[20];
char o[20];
char p[20];
char q[20];
char r[20];
char s[20];
char t[20];
char u[20];
char v[20];
char w[20];
char x[20];
char y[20];
char z[20];
char aa[20];
char ab[20];
char ac[20];

int main()
{   printf ("enter a present tense verb: \n");
    scanf ("%s", &ac);
    printf ("enter a random adjective: \n");
    scanf ("%s", &a);
    printf ("enter a random adjective: \n");
    scanf ("%s", &b);
    printf ("enter a random adjective: \n");
    scanf ("%s", &c);
    printf ("enter a random future tense verb: \n");
    scanf ("%s", &d);
    printf ("enter a random adjective: \n");
    scanf ("%s", &e);
    printf ("enter a random vegetable: \n");
    scanf ("%s", &f);
    printf ("enter a random exclamation: \n");
    scanf ("%s", &g);
    printf ("enter a random word ending in 'ing': \n");
    scanf ("%s", &h);
    printf ("enter a random future tense verb: \n");
    scanf ("%s", &i);
    printf ("enter a random noun: \n");
    scanf ("%s", &j);
    printf ("enter a random noun: \n");
    scanf ("%s", &k);
    printf ("enter a random future tense verb: \n");
    scanf ("%s", &l);
    printf ("enter a random place: \n");
    scanf ("%s", &m);
    printf ("enter a random adjective: \n");
    scanf ("%s", &n);
    printf ("enter a random future tense verb: \n");
    scanf ("%s", &o);
    printf ("enter a  defined amount: \n");
    scanf ("%s", &p);
    printf ("enter a random future tense verb: \n");
    scanf ("%s", &q);
    printf ("enter a random noun: \n");
    scanf ("%s", &r);
    printf ("enter a random noun: \n");
    scanf ("%s", &s);
    printf ("enter a random noun: \n");
    scanf ("%s", &t);
    printf ("enter a random person: \n");
    scanf ("%s", &u);
    printf ("enter a random noun: \n");
    scanf ("%s", &v);
    printf ("enter a random noun: \n");
    scanf ("%s", &w);
    printf ("enter a random vegetable: \n");
    scanf ("%s", &x);
    printf ("enter a random person: \n");
    scanf ("%s", &y);
    printf ("enter a random exclamation: \n");
    scanf ("%s", &z);
    printf ("enter a random verb ending in 'ing' : \n");
    scanf ("%s", &aa);
    printf ("enter a plural form noun: \n");
    scanf ("%s", &ab);
    printf (" Here is your completed Mad Libs \n");
    printf (" Let's build a %s snowman! First, we need to have a nice %s snowstorm,  of course on a %s day. \n Watching all that %s snow fall makes me want to %s for a bowl of %s %s! \n", ac, a, b, c, d, e, f); 
    printf (" %s \b! it's still %s and there's alot of it! Let's go! Next is to %s into the %s. \n Once that is done, we have to get busy. We make a %s and %s it in the %s. \n", g, h, i, j, k, l, m);
    printf (" It gets so %s, we can't %s it anymore. Then we make %s more and stack them on top of each other. \n We %s for %s in the driveway, and use it for the %s, eyes, and %s. \n", n, o, p, q, r, s, t);
    printf (" %s gives us a scarf, %s, %s, and %s to complete ms. \b%s \b! %s she's done! \n Finally. Now the best part, %s %s \b. \n", u, v, w, x, y, z, aa, ab);
    
    return 0;
}
